# Modified by the grok-build-hardened project; see /MODIFICATIONS.md.
[package]
license = "Apache-2.0"
name = "xai-grok-update"
version = "0.1.220-alpha.4"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
xai-grok-shell = { workspace = true }
xai-grok-telemetry = { workspace = true }
xai-grok-version = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread", "test-util"] }
